# Generated by Django 2.2.8 on 2020-03-26 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='対象箇所'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.FloatField(verbose_name='電灯'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.Location', verbose_name='対象箇所'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.FloatField(verbose_name='空調'),
        ),
    ]
