# Generated by Django 2.2.8 on 2020-03-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_weatherdata_nengetu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '場所', 'verbose_name_plural': '場所'},
        ),
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'verbose_name': 'データ', 'verbose_name_plural': 'データ'},
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
        migrations.AlterModelTable(
            name='weatherdata',
            table=None,
        ),
    ]
