# Generated by Django 2.2.8 on 2020-03-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20200326_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='data_datetime',
        ),
    ]
