# Generated by Django 2.2.8 on 2020-03-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_remove_weatherdata_data_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='temperature',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='dento',
            field=models.IntegerField(default=0, verbose_name='電灯使用量'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='goukei',
            field=models.IntegerField(default=0, verbose_name='合計'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='kuchou',
            field=models.IntegerField(default=0, verbose_name='空調使用量'),
        ),
    ]
