# Generated by Django 2.2.8 on 2020-03-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20200326_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='dento',
            new_name='dentou',
        ),
    ]
